# Permalinks
permalink:      pretty

# Setup
title:          Ingeniero y no puedo
subtitle:       El blog personal de Juanjo Salvador
baseurl:        
url:            "https://jsalvador.me"

color:          dark

author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:        juanjosalvador@netc.eu

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        3.9.1
paginate:       5
paginate_path: "/page:num/"

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
