# Site settings
title: Juanjo Salvador
author: Juanjo Salvador Piedra
email: juanjosalvador@openmailbox.org
description: Ingeniero y no puedo # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Linuxneitor
github_username:  JuanjoSalvador

# Build settings
markdown: redcarpet

# Post settings

permalink: /:title

# Collections

collections:
  talks:
    output: true

# Exclude
