# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Juanjo Salvador
tagline:          'Técnico Hacker'
description:      'Desarrollo. Debian. Software Libre.'
url:              http://juanjosalvador.es
baseurl:          /

author:
  name:           'Juanjo Salvador'
  url:            https://twitter.com/linuxneitor

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate, jekyll-gist]

github:	        'JuanjoSalvador'
twitter:        'linuxneitor'
