# Permalinks
permalink:      pretty

# Setup
title:          Ingeniero y no puedo
description:    El blog personal de Juanjo Salvador
baseurl:        "/blog"
url:            "https://jsalvador.me"

color:          dark

author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:        juanjosalvador@netc.eu
  github:       JuanjoSalvador                     # Place your GitHub username here
  twitter:      Linuxneitor                        # Place your twitter username here
  mastodon:     https://mastodon.social/@jsalvador # Place your profile URL here

# Assets
sass:
  style:        compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        3.9.1
paginate:       5
paginate_path: "/page:num/"

twitter:
  username: Linuxneitor
  card: summary
locale: es_ES

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
