# Permalinks
permalink:      pretty

# Setup
title:          El blog de Juanjo Salvador
paginate:       5
baseurl:        
url:            "https://jsalvador.me"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:        juanjosalvador@netc.eu 

# Custom vars
version:        3.4.3

# Gems
plugins: [jekyll-paginate]
